In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
data = arff.loadarff("../../../../data/dutch/dutch_census.arff")

In [3]:
# convert to pandas dataframe
dutch_df = pd.DataFrame(data[0]).astype("int32")

In [4]:
dutch_df.head()

,sex,age,household_position,household_size,prev_residence_place,citizenship,country_birth,edu_level,economic_status,cur_eco_activity,Marital_status,occupation
0,1,6,1131,112,1,1,1,5,111,135,1,21
1,2,10,1122,113,1,1,1,2,111,122,2,549
2,1,8,1122,113,1,1,1,2,111,122,2,21
3,1,12,1121,112,1,1,1,1,111,137,2,549
4,2,4,1110,114,1,1,1,2,111,138,1,549

In [5]:
dutch_df.to_csv("../../../../data/dutch/dutch_census.csv", index=False)

In [6]:
dutch_df["sex_binary"] = np.where(dutch_df["sex"] == 1, 1, 0)
dutch_df["occupation_binary"] = np.where(dutch_df["occupation"] >= 300, 1, 0)
del dutch_df["sex"]
del dutch_df["occupation"]

In [7]:
dutch_df.head()

,age,household_position,household_size,prev_residence_place,citizenship,country_birth,edu_level,economic_status,cur_eco_activity,Marital_status,sex_binary,occupation_binary
0,6,1131,112,1,1,1,5,111,135,1,1,0
1,10,1122,113,1,1,1,2,111,122,2,0,1
2,8,1122,113,1,1,1,2,111,122,2,1,0
3,12,1121,112,1,1,1,1,111,137,2,1,1
4,4,1110,114,1,1,1,2,111,138,1,0,1

In [8]:
Counter(dutch_df["edu_level"])

Counter({5: 18109, 2: 12326, 1: 4513, 3: 22672, 4: 2580, 0: 220})

In [9]:
dutch_df.shape

(60420, 12)

In [10]:
gender_and_target = []
for gender, target in zip(list(dutch_df["edu_level"]), list(dutch_df["occupation_binary"])):
    gender_and_target.append((gender, target))

Counter(gender_and_target)

Counter({(5, 0): 16211,
         (2, 1): 10059,
         (2, 0): 2267,
         (1, 1): 3781,
         (3, 0): 8051,
         (3, 1): 14621,
         (4, 0): 1466,
         (5, 1): 1898,
         (4, 1): 1114,
         (1, 0): 732,
         (0, 1): 184,
         (0, 0): 36})

In [11]:
gender_and_target = []
for gender, target in zip(list(dutch_df["sex_binary"]), list(dutch_df["occupation_binary"])):
    gender_and_target.append((gender, target))

Counter(gender_and_target)

Counter({(1, 0): 18860, (0, 1): 20370, (1, 1): 11287, (0, 0): 9903})

In [12]:
dutch_df.shape

(60420, 12)

In [13]:
# drop rows from the dataframe where "sex_binary" is 0 and "occupation_binary" is 0
# Calculate the number of rows to drop
num_rows_to_drop = int(0.8 * len(dutch_df[(dutch_df["sex_binary"] == 0) & (dutch_df["occupation_binary"] == 0)]))

# Drop the rows
dutch_df = dutch_df.drop(
    dutch_df[(dutch_df["sex_binary"] == 0) & (dutch_df["occupation_binary"] == 0)].sample(num_rows_to_drop).index
)

# Verify the shape of the dataframe after dropping rows

dutch_df.shape

(52498, 12)

In [14]:
gender_and_target = []
for gender, target in zip(list(dutch_df["sex_binary"]), list(dutch_df["occupation_binary"])):
    gender_and_target.append((gender, target))

Counter(gender_and_target)

Counter({(1, 0): 18860, (0, 1): 20370, (1, 1): 11287, (0, 0): 1981})

In [15]:
# dutch_df.to_csv("../../../../data/dutch/dutch_unprivileged.csv", index=False)

In [16]:
dutch_unprivileged = pd.read_csv("../../../../data/dutch/dutch_census_edu_level.csv")

In [17]:
Counter(dutch_unprivileged["edu_level"])

Counter({5: 18109, 2: 12326, 1: 4513, 3: 22672, 4: 2580})

In [22]:
Counter(dutch_unprivileged["occupation"])

Counter({21: 28727, 549: 31473})